package com.plura.plurabackend.booking.actions.model;

public enum BookingActionReasonCode {
    RESERVATION_NOT_FOUND,
    ACTOR_NOT_ALLOWED,
    BOOKING_NOT_ACTIVE,
    BOOKING_ALREADY_STARTED,
    CLIENT_CANCELLATION_DISABLED,
    CLIENT_RESCHEDULE_DISABLED,
    FREE_CANCELLATION_WINDOW_OPEN,
    LATE_CANCELLATION_PENALTY_APPLIES,
    RESCHEDULE_WINDOW_OPEN,
    RESCHEDULE_WINDOW_CLOSED,
    RESCHEDULE_LIMIT_REACHED,
    PROFESSIONAL_CAN_MARK_NO_SHOW,
    NO_SHOW_ONLY_AFTER_START,
    PROFESSIONAL_CANCELLATION_FULL_REFUND,
    POLICY_SNAPSHOT_FALLBACK,
    NO_PREPAID_AMOUNT,
    NO_SHOW_MARKED_MANUALLY,
    BOOKING_COMPLETED_MANUALLY
}
