app = "plura"
primary_region = "gru"

[deploy]
  strategy = "rolling"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "off"
  force_https = true
  internal_port = 3000
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "360s"
    interval = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "15s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "2gb"
  memory_mb = 2048