ALTER TABLE professional_profile
    ADD COLUMN IF NOT EXISTS logo_position_x DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS logo_position_y DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS logo_zoom DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS banner_position_x DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS banner_position_y DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS banner_zoom DOUBLE PRECISION;
