// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = "/" | "/cliente/auth/login" | "/cliente/auth/register" | "/cliente/configuracion" | "/cliente/dashboard" | "/cliente/favoritos" | "/cliente/inicio" | "/cliente/perfil" | "/cliente/reservas" | "/explorar" | "/explorar/[slug]" | "/login" | "/oauth/callback" | "/profesional/[slug]" | "/profesional/auth/login" | "/profesional/auth/register" | "/profesional/dashboard" | "/profesional/dashboard/horarios" | "/profesional/dashboard/pagina-publica" | "/profesional/dashboard/perfil-negocio" | "/profesional/dashboard/reservas" | "/profesional/dashboard/servicios" | "/profesional/pagina/[slug]" | "/reserva-confirmada" | "/reservar"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/cliente/auth/login": {}
  "/cliente/auth/register": {}
  "/cliente/configuracion": {}
  "/cliente/dashboard": {}
  "/cliente/favoritos": {}
  "/cliente/inicio": {}
  "/cliente/perfil": {}
  "/cliente/reservas": {}
  "/explorar": {}
  "/explorar/[slug]": { "slug": string; }
  "/login": {}
  "/oauth/callback": {}
  "/profesional/[slug]": { "slug": string; }
  "/profesional/auth/login": {}
  "/profesional/auth/register": {}
  "/profesional/dashboard": {}
  "/profesional/dashboard/horarios": {}
  "/profesional/dashboard/pagina-publica": {}
  "/profesional/dashboard/perfil-negocio": {}
  "/profesional/dashboard/reservas": {}
  "/profesional/dashboard/servicios": {}
  "/profesional/pagina/[slug]": { "slug": string; }
  "/reserva-confirmada": {}
  "/reservar": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
