package com.plura.plurabackend.core.booking.event.model;

public enum BookingEventType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_RESCHEDULED,
    BOOKING_COMPLETED,
    BOOKING_NO_SHOW_MARKED,
    BOOKING_FINANCIAL_RECOMPUTED,
    BOOKING_FINANCIAL_RECONCILED,
    BOOKING_REFUND_RETRY_REQUESTED,
    BOOKING_PAYOUT_RETRY_REQUESTED
}
